language: node_js

node_js:
  - node

before_script:
  - npm install -g --silent firebase-tools
  - npm install -g --silent @angular/cli

script:
  - ng build --prod

after_success:
  - firebase deploy --token $CI --non-interactive